# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-26 11:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_income'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expence',
            new_name='Expense',
        ),
    ]
